### ISSUE TITLE
Removing the '/items/' from the glossary detail page

### ISSUE THREAD

**Issue by Patric96** [oveleon/contao-glossary-bundle#46] opened 2024-09-05 14:01 UTC
Hey, i loved your glossary extension for Contao 4.13.
Unfortunately, when i try to use it with Contao 5.3, my detailpage always shows a link as following: example.de/glossary/items/entry

How can i remove the '/items'?

Thanks in advance!

**Comment by zoglo** [comment] 2024-09-05 15:38
This is a duplicate of #40. The issue has already been fixed, but has not yet been merged (see #42).

I've had to pause work on the preparations for `2.3` due to ongoing client projects. At this point, I can't give you an estimate for when we'll continue the PR, as it’s currently not a priority for Oveleon.

If it's something you need prioritized, feel free to reach out to `info@oveleon.de` to discuss getting it planned in or consider creating a temporary fork with the necessary changes.

**Comment by zoglo** [comment] 2024-09-06 07:08
@Patric96 closing this since it's a duplicate - you got your answer on how to deal with your issue

**Closed by zoglo** 2024-09-06 07:08 UTC
Labels: duplicate
